## Handling Imbalanced Data

1. Up Sampling
2. Down Sampling

In [2]:
import numpy as np
import pandas as pd

np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

In [3]:
n_class_0,n_class_1

(900, 100)

In [17]:
class_0 = pd.DataFrame({
    'feature1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' :  0 * n_class_0 
})

class_1 = pd.DataFrame({
    'feature1' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature2' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'target' : [1] * n_class_1

})

In [18]:
df=pd.concat([class_0,class_1]).reset_index(drop=True)

In [19]:
df.head()

   feature1  feature2  target
0 -1.774224  0.285744       0
1 -1.201377  0.333279       0
2  1.096257  0.531807       0
3  0.861037 -0.354766       0
4 -1.520367 -1.120815       0

In [20]:
df.tail()

     feature1  feature2  target
995  2.677156  1.092048       1
996  2.963404  0.181955       1
997  1.621476  1.877267       1
998  3.429559  3.794486       1
999  3.532273  1.679490       1

In [21]:
df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [22]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

## Up Sampling

In [25]:
from sklearn.utils import resample
df_minority_upsampled=resample(df_minority, replace=True,
                               n_samples=len(df_majority),
                               random_state=42
                               )

In [26]:
df_minority_upsampled.shape

(900, 3)

In [27]:
df_minority_upsampled.head()

     feature1  feature2  target
951  2.905343  1.495151       1
992  2.000977  1.814833       1
914  1.927957  2.280911       1
971  2.819483  2.964646       1
960  2.456515  1.833528       1

In [28]:
df_upsampled=pd.concat([df_majority,df_minority_upsampled])

In [30]:
df_upsampled['target'].value_counts()

target
0    900
1    900
Name: count, dtype: int64

## Down Sampling

In [4]:
import numpy as np
import pandas as pd

np.random.seed(123)

n_samples = 1000
class_0_ratio = 0.9
n_class_0 = int(n_samples * class_0_ratio)
n_class_1 = n_samples - n_class_0

n_class_0,n_class_1

class_0 = pd.DataFrame({
    'feature1' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'feature2' : np.random.normal(loc=0, scale=1, size=n_class_0),
    'target' :  0 * n_class_0 
})

class_1 = pd.DataFrame({
    'feature1' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'feature2' : np.random.normal(loc=2, scale=1, size=n_class_1),
    'target' : [1] * n_class_1

})

df=pd.concat([class_0,class_1]).reset_index(drop=True)

df['target'].value_counts()

target
0    900
1    100
Name: count, dtype: int64

In [5]:
df_minority = df[df['target']==1]
df_majority = df[df['target']==0]

In [12]:
from sklearn.utils import resample
df_majority_downsampled=resample(df_majority, replace=True,
                                 n_samples=len(df_minority),
                                 random_state=42)

In [13]:
df_majority_downsampled.shape

(100, 3)

In [14]:
df_majority_downsampled.head()

     feature1  feature2  target
102  0.712265  0.718151       0
435  1.199988  0.574621       0
860  0.304515 -0.759475       0
270 -1.213385  0.675504       0
106  0.179549 -0.202659       0

In [15]:
df_downsampled=pd.concat([df_majority_downsampled,df_minority])

In [16]:
df_downsampled

     feature1  feature2  target
102  0.712265  0.718151       0
435  1.199988  0.574621       0
860  0.304515 -0.759475       0
270 -1.213385  0.675504       0
106  0.179549 -0.202659       0
..        ...       ...     ...
995  1.376371  2.845701       1
996  2.239810  0.880077       1
997  1.131760  1.640703       1
998  2.902006  0.390305       1
999  2.697490  2.013570       1

[200 rows x 3 columns]

In [17]:
df_downsampled['target'].value_counts()

target
0    100
1    100
Name: count, dtype: int64