### Target Guided Ordinal Encoding

In [1]:
import pandas as pd

In [3]:
df = pd.DataFrame({
    'city' : ['New York', 'Londan', 'Paris', "Tokyo", 'New York', 'Paris'],
    'price' : [100, 80, 90, 120, 110, 95]
})

In [4]:
df

       city  price
0  New York    100
1    Londan     80
2     Paris     90
3     Tokyo    120
4  New York    110
5     Paris     95

In [5]:
mean_price_by_city = df.groupby('city')['price'].mean().to_dict()

In [6]:
mean_price_by_city

{'Londan': 80.0, 'New York': 105.0, 'Paris': 92.5, 'Tokyo': 120.0}

In [7]:
df['city_encoded'] = df['city'].map(mean_price_by_city)

In [8]:
df

       city  price  city_encoded
0  New York    100         105.0
1    Londan     80          80.0
2     Paris     90          92.5
3     Tokyo    120         120.0
4  New York    110         105.0
5     Paris     95          92.5